version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/clinical_trials
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./pdf_storage:/app/pdf_storage
    depends_on:
      - db
      - redis
    command: python app.py

  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/clinical_trials
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./pdf_storage:/app/pdf_storage
    depends_on:
      - db
      - redis
    command: celery -A app.celery worker --loglevel=info

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=clinical_trials
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A app.celery flower

volumes:
  postgres_data: